blog/urls.py
from django.urls import path
from blog import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.blog, name='Blog'),
    path('categoria/<int:categoria_id>/', views.categoria, name='categoria'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name='carro'
urlpatterns = [
    path('agregar/<int:curso_id>/', views.agregar_carro, name='agregar'),
    path('eliminar/<int:curso_id>/', views.eliminar_carro, name='eliminar'),
    path('restar/<int:curso_id>/', views.restar_carro, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

curso/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.curso, name='Curso'),
    path('total/', views.cursostotal, name='CursosTotal'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

developer/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),    
    url(r'^', include('aplicacionweb.urls')),
    url(r'servicios/', include('servicios.urls')),
    url(r'blog/', include('blog.urls')),
    url(r'contact/', include('contact.urls')),
    url(r'curso/', include('curso.urls')),
    url(r'carro/', include('carro.urls')),
    url(r'perfil/', include('perfil.urls')),
    url(r'portafolio/', include('portafolio.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/models.py
from django.db import models

# Create your models here.

curso/models.py
from django.db import models
from django.db.models.base import Model
from cloudinary.models import CloudinaryField

# Create your models here.
class categoriaCurso(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateField(auto_now=True)
    update=models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'categoriacurso'
        verbose_name_plural = 'categoriacursos'

    def __str__(self):
        return self.nombre

class Curso(models.Model):
    nombre=models.CharField(max_length=50)
    categorias=models.ForeignKey(categoriaCurso, on_delete=models.CASCADE)
    imagen=CloudinaryField('imagen')
    precio=models.FloatField()
    disponivilidad=models.BooleanField(default=True)
    created=models.DateField(auto_now_add=True)
    update=models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'curso'
        verbose_name_plural = 'cursos'
        
    def __str__(self):
        return self.nombre

carro/views.py
from django.shortcuts import redirect, render
from .carro import Carro
from curso.models import Curso

# Create your views here.
def agregar_carro(request, curso_id):
    carro=Carro(request)
    curso=Curso.objects.get(id=curso_id)
    carro.agregar(curso=curso)
    return redirect('Curso')

def eliminar_carro(request, curso_id):
    carro=Carro(request)
    curso=Curso.objects.get(id=curso_id)
    carro.eliminar(curso=curso)
    return redirect('Curso')

def restar_carro(request, curso_id):
    carro=Carro(request)
    curso=Curso.objects.get(id=curso_id)
    carro.restar_curso(curso=curso)
    return redirect('Curso')

def limpiar_carro(request):
    carro=Carro(request)
    carro.limpiar_carro()
    return redirect('Curso')

curso/views.py
from django.shortcuts import render
from .models import Curso

# Create your views here.
def curso(request):
    curso=Curso.objects.all()
    return render(request,"curso/curso.html", {'cursos': curso})

def cursostotal(request):
    curso=Curso.objects.all()
    return render(request,"curso/cursostotal.html", {'cursos': curso})

curso/templates/carro/widget.html
<table class="table">
    <thead>
        <tr>
            <th scope="col">Imagen</th>
            <th scope="col">Curso</th>
            <!-- <th scope="col">producto</th> -->
            <th scope="col">Total</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
        <tr>
            <td>
                <img src='{{value.imagen}}' height="55rem" />


            </td>
            <td>
                {{value.nombre}}
            </td>
            <!-- <td>
                {{value.cantidad}}
            </td> -->
            <td>
                <!-- <a href="{% url 'carro:agregar' value.curso_id %}" class="btn btn-sm btn-success">+</a> -->
                <!-- <a href="{% url 'carro:restar' value.curso_id %}" class="btn btn-sm btn-success">-</a><br> -->
                {{value.precio}} $

            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr colspan='3'>
            <td class="alert alert-danger text-center">
                No tienes actualmente un curso
            </td>

        </tr>
        {% endif %}
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                Total {{importe_total_carro}}
            </td>
        </tr>
    </tfoot>
</table>